<%@ Page Title="" Language="C#" MasterPageFile="~/log.master" AutoEventWireup="true" CodeFile="aboutus.aspx.cs" Inherits="aboutus" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <p style="font-family: arial, helvetica, sans-serif; font-size: 16px; color: rgb(0, 0, 0); margin: 5px 0px 8px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    We are a group of IT professionals enthusiastic in creating quality free tools and content on the Internet. The main purpose of this website is to provide a comprehensive collection of free online calculators for ease of public use. This site was launched on calculators.info first in 2007. In 2008, we migrated to calculator.net.</p>
<p style="font-family: arial, helvetica, sans-serif; font-size: 16px; color: rgb(0, 0, 0); margin: 5px 0px 8px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    The calculators on this site were grouped into 4 sections:<span>&nbsp;</span><a href="https://www.calculator.net/financial-calculator.html" style="color: rgb(0, 102, 153); text-decoration: none;">financial</a>,<span>&nbsp;</span><a href="https://www.calculator.net/fitness-and-health-calculator.html" style="color: rgb(0, 102, 153); text-decoration: underline;">fitness &amp; health</a>,<span>&nbsp;</span><a href="https://www.calculator.net/math-calculator.html" style="color: rgb(0, 102, 153); text-decoration: underline;">math</a>, and<span>&nbsp;</span><a href="https://www.calculator.net/other-calculator.html" style="color: rgb(0, 102, 153); text-decoration: underline;">others</a>. All of the calculators were developed in-house. Some calculators use open-source JavaScript components under different open-source licenses. More than 90% of the calculators are based on well-known formulas or equations from textbooks, such as the mortgage calculator, BMI calculator, etc. If formulas are controversial, we provide 
    the results of all popular formulas, as can be seen in the Ideal Weight Calculator. Calculators such as the love calculator that are solely meant for amusement are based on internal formulas. The results of the financial calculators were reviewed by our financial advisors, who work for major personal financial advising firms. The results of the health calculators were reviewed and approved by local medical doctors. More than 99% of the descriptive content was developed in-house with a small amount of content taken from wikipedia.org under the GNU Free Documentation License. The descriptive content of the financial calculators was created and reviewed by our financial team. The descriptive content of the health calculators was reviewed by local medical doctors.</p>
<br />
<span style="color: rgb(0, 0, 0); font-family: arial, helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">This site is owned and operated by NOVAC Tech .pvt.Ltd.</span>
</asp:Content>

