<%@ Page Title="" Language="C#" MasterPageFile="~/log.master" AutoEventWireup="true" CodeFile="overview.aspx.cs" Inherits="overview" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <p>
    <br />
    <asp:ScriptManager ID="ScriptManager1" runat="server">
    </asp:ScriptManager>
</p>
<asp:UpdatePanel ID="UpdatePanel1" runat="server">
    <ContentTemplate>
        <asp:AdRotator ID="AdRotator1" runat="server" DataSourceID="XmlDataSource1" OnAdCreated="AdRotator1_AdCreated" />
        <asp:XmlDataSource ID="XmlDataSource1" runat="server" DataFile="~/ad.xml"></asp:XmlDataSource>
        <asp:Timer ID="Timer1" runat="server" Interval="2000">
        </asp:Timer>
    </ContentTemplate>
</asp:UpdatePanel>
<p>
</p>
<p style="margin: 0.5em 0px; color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    The process of conversion depends on the specific situation and the intended purpose. This may be governed by regulation,<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Contract" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Contract">contract</a>,<span>&nbsp;</span><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Technical_specifications" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Technical specifications">technical specifications</a><span>&nbsp;</span>or other published<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Technical_standard" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Technical standard">standards</a>. Engineering judgment may include such factors as:</p>
<ul style="list-style-image: url(''); margin: 0.3em 0px 0px 1.6em; padding: 0px; color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <li style="margin-bottom: 0.1em;">The<span>&nbsp;</span><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Precision_and_accuracy" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Precision and accuracy">precision and accuracy</a><span>&nbsp;</span>of measurement and the associated<span>&nbsp;</span><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Uncertainty_of_measurement" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Uncertainty of measurement">uncertainty of measurement</a>.</li>
    <li style="margin-bottom: 0.1em;">The statistical<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Confidence_interval" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Confidence interval">confidence interval</a><span>&nbsp;</span>or<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Tolerance_interval" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Tolerance interval">tolerance interval</a><span>&nbsp;</span>of the initial measurement.</li>
    <li style="margin-bottom: 0.1em;">The number of<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Significant_figures" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Significant figures">significant figures</a><span>&nbsp;</span>of the measurement.</li>
    <li style="margin-bottom: 0.1em;">The intended use of the measurement including the<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Engineering_tolerance" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Engineering tolerance">engineering tolerances</a>.</li>
    <li style="margin-bottom: 0.1em;">Historical definitions of the units and their derivatives used in old measurements; e.g.,<span>&nbsp;</span><a class="mw-redirect" href="https://en.wikipedia.org/wiki/International_foot" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="International foot">international foot</a><span>&nbsp;</span>vs. US<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Foot_(unit)#Survey_foot" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Foot (unit)">survey foot</a>.</li>
</ul>
<p style="margin: 0.5em 0px; color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    Some conversions from one system of units to another need to be exact, without increasing or decreasing the precision of the first measurement. This is sometimes called<span>&nbsp;</span><i>soft conversion</i>. It does not involve changing the physical configuration of the item being measured.</p>
<p style="margin: 0.5em 0px; color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    By contrast, a<span>&nbsp;</span><i>hard conversion</i><span>&nbsp;</span>or an<span>&nbsp;</span><i>adaptive conversion</i><span>&nbsp;</span>may not be exactly equivalent. It changes the measurement to convenient and workable numbers and units in the new system. It sometimes involves a slightly different configuration</p>
<p>
</p>
<p>
    <asp:Button ID="Button1" runat="server" Text="UNIT CONVERSIONS" />
    <img alt="No img found" src="over.jfif" style="width: 700px; height: 122px" /></p>
<p>
    &nbsp;</p>
<ul class="b_vList b_divsec" style="border: 0px; border-collapse: collapse; border-spacing: 0px; list-style: none; margin: 0px; padding: 0px; line-height: 20px; color: rgb(102, 102, 102); font-family: Roboto, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <li data-priority="" style="border: 0px; border-collapse: collapse; border-spacing: 0px; list-style: none; margin: 0px; padding: 0px 0px 10px;">
        <div>
            In order to have accuracy and avoid confusion in measurement, we need to convert one unit to another. For instance, we<strong style="font-weight: 700;"><span>&nbsp;</span>do not measure the length of a pencil in kilometres,</strong><span>&nbsp;</span>in such case one have to convert kilometre (km) to centimetre (cm). Generally, the conversion of one unit to another unit of the same quantity is performed using multiplicative conversion factors. Let’s see how to convert a different unit of length and mass.</div>
    </li>
</ul>
<p>
    <asp:Button ID="Button2" runat="server" Text="EMI CONVERSIONS" />
</p>
    <p>
        <img alt="No img" src="emioverview.png" style="width: 751px; height: 478px" /></p>
    <p>
        &nbsp;</p>
    <p>
        &nbsp;</p>
    <p style="margin: 0.5em 0px; color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        An<span>&nbsp;</span><b>equated monthly installment (EMI)</b><span>&nbsp;</span>is defined by<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Investopedia" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Investopedia">Investopedia</a><span>&nbsp;</span>as &quot;A fixed payment amount made by a borrower to a lender at a specified date each calendar month. Equated monthly installments are used to pay off both<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Interest" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Interest">interest</a><span>&nbsp;</span>and<span>&nbsp;</span><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Principal_sum" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Principal sum">principal</a><span>&nbsp;</span>each month, so that over a specified number of years, the loan is fully paid off along with interest.&quot;</p>
    <p style="margin: 0.5em 0px; color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        It further explains that, with most common types of loans, such as real estate<span>&nbsp;</span><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Mortgages" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Mortgages">mortgages</a>, the borrower makes fixed periodic payments to the lender over the course of several years with the goal of retiring the loan. EMIs differ from variable payment plans, in which the borrower is able to pay higher payment amounts at his or her discretion. In EMI plans, borrowers are<span>&nbsp;</span><a class="new" href="https://en.wikipedia.org/w/index.php?title=Mostly&amp;action=edit&amp;redlink=1" style="text-decoration: none; color: rgb(221, 51, 51); background: none;" title="Mostly (page does not exist)">mostly</a><span>&nbsp;</span>only allowed one fixed payment amount each month.</p>
    <p style="margin: 0.5em 0px; color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        The benefit of an EMI for borrowers is that they know precisely how much money they will need to pay toward their loan each month, making the<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Personal_budget" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Personal budget">personal budgeting</a><span>&nbsp;</span>process easier</p>
<p>
</p>
<p>
    &nbsp;</p>
<p>
</p>
<asp:Button ID="Button3" runat="server" Text="MONEY EXCHANGE" />
    <br />
<br />
    <img alt="No img" src="moneyoverview.jpg" style="width: 1024px; height: 461px" /><br />
    <br />
    <br />
    <p style="margin: 0.5em 0px; color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        In<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Finance" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Finance">finance</a>, an<span>&nbsp;</span><b>exchange rate</b><span>&nbsp;</span>is the rate at which one<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Currency" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Currency">currency</a><span>&nbsp;</span>will be exchanged for another currency. Currencies are most commonly national currencies, but may be sub-national as in the case of Hong Kong or supra-national as in the case of the euro.</p>
    <p style="margin: 0.5em 0px; color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        The exchange rate is also regarded as the value of one country&#39;s currency in relation to another currency.<sup id="cite_ref-1" class="reference" style="line-height: 1; unicode-bidi: isolate; white-space: nowrap; font-weight: normal; font-style: normal; font-size: 11.2px;"><a href="https://en.wikipedia.org/wiki/Exchange_rate#cite_note-1" style="text-decoration: none; color: rgb(6, 69, 173); background: none;">[1]</a></sup><span>&nbsp;</span>For example, an<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Interbank_lending_market" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Interbank lending market">interbank exchange rate</a><span>&nbsp;</span>of 114<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Japanese_yen" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Japanese yen">Japanese yen</a><span>&nbsp;</span>to the<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/United_States_dollar" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="United States dollar">United 
        States dollar</a><span>&nbsp;</span>means that ¥114 will be exchanged for US$1 or that US$1 will be exchanged for ¥114. In this case it is said that the price of a dollar in relation to yen is ¥114, or equivalently that the price of a yen in relation to dollars is $1/114.</p>
    <p style="margin: 0.5em 0px; color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        Each country determines the<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Exchange_rate_regime" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Exchange rate regime">exchange rate regime</a><span>&nbsp;</span>that will apply to its currency. For example, a currency may be<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Floating_exchange_rate" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Floating exchange rate">floating</a>,<span>&nbsp;</span><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Fixed_exchange_rate" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Fixed exchange rate">pegged (fixed)</a>, or a hybrid. Governments can impose certain limits and controls on exchange rates. Countries can also have a strong or weak currency. There is no agreement in the economic literature on the optimal national exchange rate (unlike on the subject of trade where free trade is considered 
        optimal).<sup id="cite_ref-:0_2-0" class="reference" style="line-height: 1; unicode-bidi: isolate; white-space: nowrap; font-weight: normal; font-style: normal; font-size: 11.2px;"><a href="https://en.wikipedia.org/wiki/Exchange_rate#cite_note-:0-2" style="text-decoration: none; color: rgb(6, 69, 173); background: none;">[2]</a></sup><span>&nbsp;</span>Rather, national exchange rate regimes reflect political considerations</p>
    <br />
    <br />
<br />
</asp:Content>

