<%@ Page Title="" Language="C#" MasterPageFile="~/log.master" AutoEventWireup="true" CodeFile="terms.aspx.cs" Inherits="terms" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <p style="font-family: arial, helvetica, sans-serif; font-size: 16px; color: rgb(0, 0, 0); margin: 5px 0px 8px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <b>Acceptance of Terms</b></p>
<p style="font-family: arial, helvetica, sans-serif; font-size: 16px; color: rgb(0, 0, 0); margin: 5px 0px 8px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    Maple Tech International LLC. (&quot;Company&quot;) provides this website at calculator.net (referred to hereafter as &quot;the Website&quot;) for use by consumers and businesses. By using the Website in any way, you are agreeing to comply with the Terms of Use. Should you object to any term or condition of the Terms of Use or any guideline of the Website, your only recourse is to immediately discontinue use of the Website.</p>
<p style="font-family: arial, helvetica, sans-serif; font-size: 16px; color: rgb(0, 0, 0); margin: 5px 0px 8px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <b>Changes to the Terms of Use</b></p>
<p style="font-family: arial, helvetica, sans-serif; font-size: 16px; color: rgb(0, 0, 0); margin: 5px 0px 8px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    We reserve the right, at our sole discretion, to change, modify, or alter the Terms of Use at any time. Such changes shall become effective immediately upon the posting thereof. The most current version of the Terms of Use will be linked from the footer of the Website. You must review the Terms of Use on a regular basis to keep yourself apprised of any changes.</p>
<p style="font-family: arial, helvetica, sans-serif; font-size: 16px; color: rgb(0, 0, 0); margin: 5px 0px 8px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <b>Conduct</b></p>
<p style="font-family: arial, helvetica, sans-serif; font-size: 16px; color: rgb(0, 0, 0); margin: 5px 0px 8px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    You agree not to post any text, files, images, video, audio, or other materials (&quot;Content&quot;) or use the Website in any way that:</p>
<ul style="color: rgb(0, 0, 0); font-family: arial, helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <li style="font-family: arial, helvetica, sans-serif; font-size: 16px; color: rgb(0, 0, 0);">infringes any patent, trademark, trade secret, copyright, or other proprietary rights of any party;</li>
    <li style="font-family: arial, helvetica, sans-serif; font-size: 16px; color: rgb(0, 0, 0);">violates any state, federal, or other law;</li>
    <li style="font-family: arial, helvetica, sans-serif; font-size: 16px; color: rgb(0, 0, 0);">threatens, harasses, or is libelous;</li>
    <li style="font-family: arial, helvetica, sans-serif; font-size: 16px; color: rgb(0, 0, 0);">is harmful to minors;</li>
    <li style="font-family: arial, helvetica, sans-serif; font-size: 16px; color: rgb(0, 0, 0);">contains self-benefiting advertising or marketing in public areas of the Website that have not been paid for and are not designated for the addition of promotional content;</li>
    <li style="font-family: arial, helvetica, sans-serif; font-size: 16px; color: rgb(0, 0, 0);">produces Software viruses or code harmful to other computers;</li>
    <li style="font-family: arial, helvetica, sans-serif; font-size: 16px; color: rgb(0, 0, 0);">disrupts the normal dialogue of users of the Website;</li>
    <li style="font-family: arial, helvetica, sans-serif; font-size: 16px; color: rgb(0, 0, 0);">employs misleading or false information;</li>
    <li style="font-family: arial, helvetica, sans-serif; font-size: 16px; color: rgb(0, 0, 0);">uses forged headers or other items to manipulate identifiers in order to disguise the origin of</li>
    <li style="font-family: arial, helvetica, sans-serif; font-size: 16px; color: rgb(0, 0, 0);">&nbsp;Content.</li>
</ul>
<p style="font-family: arial, helvetica, sans-serif; font-size: 16px; color: rgb(0, 0, 0); margin: 5px 0px 8px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <b>Privacy</b></p>
<p style="font-family: arial, helvetica, sans-serif; font-size: 16px; color: rgb(0, 0, 0); margin: 5px 0px 8px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    Please review our Privacy Policy for details on the Company&#39;s collection, disclosure, and use of personally identifiable information and privacy matters. Use of the Website is based on your agreement to the Privacy Policy and Terms of Use.</p>
<p style="font-family: arial, helvetica, sans-serif; font-size: 16px; color: rgb(0, 0, 0); margin: 5px 0px 8px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <b>Content</b></p>
<p style="font-family: arial, helvetica, sans-serif; font-size: 16px; color: rgb(0, 0, 0); margin: 5px 0px 8px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    This Website and some of the Content on this Website contain links to other resources on the Internet. Such links are provided as aids to assist you in identifying and locating other Internet resources that may be of interest to you, and are not intended to state or imply that Company sponsors, endorses, are affiliated or associated with, or are legally authorized to use any trade name, registered trademark, logo, legal or official seal, or copyrighted symbol that may be reflected in said links.</p>
<p style="font-family: arial, helvetica, sans-serif; font-size: 16px; color: rgb(0, 0, 0); margin: 5px 0px 8px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    Information or calculation results at our Website may be outdated due to the date and the method of the collection or may be incorrect. If you find information or calculation results on the Website that you believe to be in error, please contact us with the specifics and we will investigate the matter and where we are allowed by our data source we will update the information.</p>
<p>
    &nbsp;</p>
<p>
    &nbsp;</p>
</asp:Content>

